import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import test from 'node:test';
import {fileURLToPath} from 'node:url';
import {CodexReviewJobManager,HelperProcessInspector} from '../runtime.ts';

const helper=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../../skills/codex-review-partner/scripts/process_identity.py');
const inspector=new HelperProcessInspector(helper);
async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'codex-reconcile-'));t.after(()=>rm(root,{recursive:true,force:true}));const cache=path.join(root,'cache'),jobs=path.join(cache,'jobs'),reservations=path.join(cache,'reservations');await mkdir(jobs,{recursive:true});await mkdir(reservations);return{root,cache,jobs,reservations}}
function identity(pid){const value=inspector.snapshot(pid);if(!value)throw Error(`missing process ${pid}`);return{pgid:value.pgid,sid:value.sid,startTime:value.startIdentity}}
async function persist(f,name,overrides={}){const output=path.join(f.root,`${name}.md`),reservationFile=path.join(f.reservations,`${name}.reserve`),stateFile=path.join(f.jobs,`${name}.state.json`),jobNonce=`nonce-${name}`;const state={jobId:name,jobNonce,action:'start',reviewType:'implementation-review',verdictProfile:'generic-implementation',status:'starting',summary:'',cwd:f.root,output,stdoutLog:path.join(f.jobs,`${name}.stdout`),stderrLog:path.join(f.jobs,`${name}.stderr`),stateFile,reservationFile,stagingOutput:path.join(f.jobs,`${name}.staging`),launcherStatus:path.join(f.jobs,`${name}.status`),processIdentityFile:path.join(f.jobs,`${name}.identity`),startedAt:new Date().toISOString(),ownerPid:999999,ownerStartIdentity:'1',deliveryId:`delivery-${name}`,deliveryState:'pending',deliveryAttempts:0,...overrides};await writeFile(reservationFile,`${state.jobId}\n${state.jobNonce}\n${state.output}\n`);await writeFile(stateFile,JSON.stringify(state));return state}
async function alive(pid){try{process.kill(pid,0);return true}catch{return false}}
async function waitDead(pid){for(let i=0;i<80;i++){if(!await alive(pid))return;await new Promise(r=>setTimeout(r,25))}throw Error(`pid ${pid} survived`)}

test('startup releases starting ownership and emits one interrupted completion',async t=>{const f=await fixture(t),state=await persist(f,'starting');await writeFile(state.stagingOutput,'x');const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false});await m.activate();assert.equal(m.status('starting').status,'interrupted');assert.equal(notes.length,1);await assert.rejects(readFile(state.reservationFile));await assert.rejects(readFile(state.stagingOutput));await m.shutdown()});

test('startup leaves another live manager ownership and reservation untouched',async t=>{const f=await fixture(t),owner=identity(process.pid),state=await persist(f,'foreign',{ownerPid:process.pid,ownerStartIdentity:owner.startTime});const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false});await m.activate();assert.equal(m.status('foreign'),undefined);assert.equal(notes.length,0);assert.match(await readFile(state.reservationFile,'utf8'),/^foreign/);await m.shutdown()});

test('transient owner inspection uncertainty leaves foreign ownership and reservation untouched',async t=>{const f=await fixture(t),state=await persist(f,'foreign-unknown',{ownerPid:42,ownerStartIdentity:'owner-start',ownerBootId:'linux:boot'}),notes=[],transient={preflight:()=>({platform:'linux',bootId:'linux:boot'}),snapshot:()=>{throw Error('transient process inspection failure')},listSession:()=>[]};const m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,processInspector:transient,onComplete:e=>notes.push(e),deliveryEvidence:()=>false});await m.activate();assert.equal(m.status('foreign-unknown'),undefined);assert.equal(notes.length,0);assert.match(await readFile(state.reservationFile,'utf8'),/^foreign-unknown/);await m.shutdown()});

test('hot-install migration trusts a matching live v2 supervisor when legacy state lacks owner and launcher identities',async t=>{const f=await fixture(t),leader=spawn('python3',['-c','import time; time.sleep(60)'],{detached:true,stdio:'ignore'});t.after(()=>{try{process.kill(-leader.pid,'SIGKILL')}catch{}});await new Promise(r=>setTimeout(r,30));const live=identity(leader.pid),platform=inspector.preflight(),state=await persist(f,'hot-install',{status:'running',ownerPid:undefined,ownerStartIdentity:undefined,ownerBootId:undefined,pid:999999,pgid:999999,sid:undefined,processStartIdentity:undefined,bootId:undefined});await writeFile(state.processIdentityFile,JSON.stringify({protocolVersion:2,adapterVersion:1,platform:platform.platform,nonce:state.jobNonce,bootId:platform.bootId,phase:'ready',leaderPid:leader.pid,leaderPgid:live.pgid,leaderSid:live.sid,leaderStartIdentity:live.startTime}));const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false});await m.activate();assert.equal(m.status('hot-install'),undefined);assert.equal(notes.length,0);assert.match(await readFile(state.reservationFile,'utf8'),/^hot-install/);await m.shutdown()});

test('matching identity and nonce escalates TERM to KILL and waits for exit before delivery',async t=>{const f=await fixture(t),child=spawn('python3',['-c','import signal,time; signal.signal(signal.SIGTERM, signal.SIG_IGN); time.sleep(60)'],{detached:true,stdio:'ignore'});t.after(()=>{try{process.kill(-child.pid,'SIGKILL')}catch{}});await new Promise(r=>setTimeout(r,50));const id=identity(child.pid),state=await persist(f,'matching',{status:'running',pid:child.pid,pgid:id.pgid,sid:id.sid,processStartIdentity:id.startTime});const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false,killGraceMs:50});await m.activate();await waitDead(child.pid);assert.equal(m.status('matching').classification,'CODEX_REVIEW_INTERRUPTED');assert.equal(notes.length,1);await assert.rejects(readFile(state.reservationFile));await m.shutdown()});

test('dead and mismatched identities are never signalled',async t=>{const f=await fixture(t);await persist(f,'dead',{status:'running',pid:999999,pgid:999999,sid:999999,processStartIdentity:'1'});const child=spawn('python3',['-c','import time; time.sleep(60)'],{detached:true,stdio:'ignore'});t.after(()=>{try{process.kill(-child.pid,'SIGKILL')}catch{}});await new Promise(r=>setTimeout(r,30));const id=identity(child.pid);await persist(f,'mismatch',{status:'running',pid:child.pid,pgid:id.pgid,sid:id.sid,processStartIdentity:`${id.startTime}x`});const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false,killGraceMs:30});await m.activate();assert.equal(await alive(child.pid),true);assert.equal(m.status('dead').classification,'CODEX_REVIEW_INTERRUPTED');assert.equal(m.status('mismatch').classification,'CODEX_REVIEW_ORPHAN_IDENTITY_UNCERTAIN');assert.equal(notes.length,2);await m.shutdown()});

test('mismatched job nonce preserves another reservation and all failed-cleanup evidence',async t=>{const f=await fixture(t),child=spawn('python3',['-c','import time; time.sleep(60)'],{detached:true,stdio:'ignore'});t.after(()=>{try{process.kill(-child.pid,'SIGKILL')}catch{}});await new Promise(r=>setTimeout(r,30));const id=identity(child.pid),state=await persist(f,'nonce',{status:'running',pid:child.pid,pgid:id.pgid,sid:id.sid,processStartIdentity:id.startTime});await writeFile(state.reservationFile,`other-job\nother-nonce\n${state.output}\n`);for(const file of [state.stagingOutput,state.launcherStatus,state.processIdentityFile])await writeFile(file,'evidence');const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false,killGraceMs:30});await m.activate();assert.equal(await alive(child.pid),true);assert.equal(m.status('nonce').classification,'CODEX_REVIEW_ORPHAN_IDENTITY_UNCERTAIN');assert.match(await readFile(state.reservationFile,'utf8'),/^other-job/);for(const file of [state.stagingOutput,state.launcherStatus,state.processIdentityFile])assert.equal(await readFile(file,'utf8'),'evidence');assert.equal(notes.length,1);await m.shutdown()});

function deterministicProcess(pid,pgid,sid,startIdentity,state='R'){return{pid,ppid:1,pgid,sid,state,startIdentity,alive:true,zombie:false}}
function deterministicCleanup(records,mutateOnStop){
  const table=new Map(records.map(row=>[row.pid,{...row}])),events=[];
  const inspector={preflight:()=>({platform:'linux',bootId:'linux:boot'}),snapshot:pid=>table.get(pid),listSession:sid=>[...table.values()].filter(row=>row.sid===sid),listGroup:pgid=>[...table.values()].filter(row=>row.pgid===pgid)};
  const signalProcess=(pid,signum)=>{events.push(['pid',pid,signum]);if(signum==='SIGSTOP'){const current=table.get(pid);if(current)table.set(pid,{...current,state:'T'});mutateOnStop?.(pid,table)}return true};
  const signalGroup=(pgid,signum)=>{events.push(['group',pgid,signum]);for(const [pid,current] of [...table])if(current.pgid===pgid){if(signum==='SIGSTOP')table.set(pid,{...current,state:'T'});else if(signum==='SIGCONT')table.set(pid,{...current,state:'R'});else if(signum==='SIGKILL')table.delete(pid)}return true};
  return{inspector,signalProcess,signalGroup,events,table};
}
async function persistLegacyV1(f,name,cleanup){const state=await persist(f,name,{status:'running',pid:10,pgid:10,processStartIdentity:'linux-jiffies:100',bootId:'linux:boot'});assert.equal(Object.hasOwn(state,'sid'),false);await writeFile(state.processIdentityFile,JSON.stringify({protocolVersion:1,nonce:state.jobNonce,codexPid:20,codexPgid:20,processStartIdentity:'200',bootId:'boot'}));const m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,processInspector:cleanup.inspector,signalProcess:cleanup.signalProcess,signalGroup:cleanup.signalGroup,deliveryEvidence:()=>false,killGraceMs:0});await m.activate();return{state,m}}

test('legacy Linux v1 evidence without sid anchors TERM and KILL and reconciles cleanly',async t=>{const f=await fixture(t),cleanup=deterministicCleanup([deterministicProcess(10,10,10,'linux-jiffies:100'),deterministicProcess(20,20,20,'linux-jiffies:200')]),{state,m}=await persistLegacyV1(f,'legacy-v1',cleanup);assert.equal(m.status('legacy-v1').classification,'CODEX_REVIEW_INTERRUPTED');assert.deepEqual([...cleanup.table],[]);assert.ok(cleanup.events.some(([kind,pid,signum])=>kind==='pid'&&pid===20&&signum==='SIGSTOP'));const killIndex=cleanup.events.findIndex(([kind,pgid,signum])=>kind==='group'&&pgid===20&&signum==='SIGKILL'),anchorIndex=cleanup.events.findLastIndex(([kind,pid,signum],index)=>index<killIndex&&kind==='pid'&&pid===20&&signum==='SIGSTOP');assert.ok(anchorIndex>=0&&anchorIndex<killIndex);await assert.rejects(readFile(state.reservationFile));await m.shutdown()});

test('legacy and launcher inspection failures persist cleanup uncertainty',async t=>{for(const phase of ['legacy','launcher']){const f=await fixture(t),name=`inspection-${phase}`,cleanup=deterministicCleanup([deterministicProcess(10,10,10,'linux-jiffies:100'),deterministicProcess(20,20,20,'linux-jiffies:200')]),state=await persist(f,name,{status:'running',pid:10,pgid:10,processStartIdentity:'linux-jiffies:100',bootId:'linux:boot'});await writeFile(state.processIdentityFile,JSON.stringify({protocolVersion:1,nonce:state.jobNonce,codexPid:20,codexPgid:20,processStartIdentity:'200',bootId:'boot'}));if(phase==='legacy')cleanup.inspector.listGroup=()=>{throw Error('legacy inspection failed')};else cleanup.inspector.listSession=()=>{throw Error('launcher inspection failed')};const m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,processInspector:cleanup.inspector,signalProcess:cleanup.signalProcess,signalGroup:cleanup.signalGroup,deliveryEvidence:()=>false,killGraceMs:0});await m.activate();assert.equal(m.status(name).classification,'CODEX_REVIEW_ORPHAN_IDENTITY_UNCERTAIN',phase);assert.match(await readFile(state.reservationFile,'utf8'),new RegExp(`^${name}`));await m.shutdown()}});

test('dead launcher with surviving persisted group fails closed without signalling possible reuse',async t=>{const f=await fixture(t),cleanup=deterministicCleanup([deterministicProcess(11,10,10,'linux-jiffies:110')]),state=await persist(f,'dead-launcher-group',{status:'running',pid:10,pgid:10,sid:10,processStartIdentity:'linux-jiffies:100',bootId:'linux:boot'});await writeFile(state.stagingOutput,'staging-evidence');await writeFile(state.launcherStatus,'launcher-evidence');const m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,processInspector:cleanup.inspector,signalProcess:cleanup.signalProcess,signalGroup:cleanup.signalGroup,deliveryEvidence:()=>false,killGraceMs:0});await m.activate();assert.equal(m.status('dead-launcher-group').classification,'CODEX_REVIEW_ORPHAN_IDENTITY_UNCERTAIN');assert.deepEqual([...cleanup.table].map(([pid])=>pid),[11]);assert.equal(cleanup.events.some(([kind])=>kind==='group'),false);assert.match(await readFile(state.reservationFile,'utf8'),/^dead-launcher-group/);assert.equal(await readFile(state.stagingOutput,'utf8'),'staging-evidence');assert.equal(await readFile(state.launcherStatus,'utf8'),'launcher-evidence');await m.shutdown()});

test('group disappearance is accepted but reused or mismatched anchors are never group-signalled',async t=>{for(const mode of ['disappeared','reused','pgid-mismatch']){const f=await fixture(t),cleanup=deterministicCleanup([deterministicProcess(10,10,10,'linux-jiffies:100'),deterministicProcess(20,20,20,'linux-jiffies:200')],(pid,table)=>{if(pid!==20)return;if(mode==='disappeared')table.delete(pid);else if(mode==='reused')table.set(pid,deterministicProcess(20,20,20,'linux-jiffies:reused','T'));else table.set(pid,deterministicProcess(20,21,20,'linux-jiffies:200','T'))}),{state,m}=await persistLegacyV1(f,`legacy-${mode}`,cleanup);assert.equal(cleanup.events.some(([kind,pgid])=>kind==='group'&&pgid===20),false,mode);if(mode==='disappeared'){assert.equal(m.status(`legacy-${mode}`).classification,'CODEX_REVIEW_INTERRUPTED');await assert.rejects(readFile(state.reservationFile))}else{assert.equal(m.status(`legacy-${mode}`).classification,'CODEX_REVIEW_ORPHAN_IDENTITY_UNCERTAIN');assert.match(await readFile(state.reservationFile,'utf8'),new RegExp(`^legacy-${mode}`))}await m.shutdown()}});

test('durable delivery state resolves crash boundaries without zero or duplicate completion',async t=>{const f=await fixture(t);await persist(f,'pending',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:new Date().toISOString(),deliveryState:'pending'});await persist(f,'recorded',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:new Date().toISOString(),deliveryState:'delivering'});await persist(f,'unrecorded',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:new Date().toISOString(),deliveryState:'delivering'});const notes=[],recorded=new Set(['delivery-recorded']),evidence=id=>recorded.has(id);const first=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:evidence});await first.activate();assert.deepEqual(notes.map(x=>x.jobId).sort(),['pending','unrecorded']);assert.equal(first.status('recorded').deliveryState,'delivered');for(const event of notes){recorded.add(event.deliveryId);assert.equal(first.confirmDelivery(event.deliveryId),true)}await first.shutdown();const after=[],second=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>after.push(e),deliveryEvidence:evidence});await second.activate();assert.equal(after.length,0);for(const id of ['pending','recorded','unrecorded'])assert.equal(second.status(id).deliveryState,'delivered');await second.shutdown()});

test('actual top-level custom_message session evidence prevents restart redelivery',async t=>{const f=await fixture(t),state=await persist(f,'top-level',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:new Date().toISOString(),deliveryState:'delivering'}),sessions=path.join(f.root,'sessions');await mkdir(sessions);await writeFile(path.join(sessions,'session.jsonl'),JSON.stringify({type:'custom_message',customType:'codex-review-completion',details:{deliveryId:state.deliveryId}})+'\n');const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,sessionsDir:sessions,onComplete:e=>notes.push(e)});await m.activate();assert.equal(notes.length,0);assert.equal(m.status('top-level').deliveryState,'delivered');await m.shutdown()});

test('retention never prunes pending or delivering exactly-once evidence',async t=>{const f=await fixture(t),now=new Date().toISOString(),old=new Date(Date.now()-10*86400_000).toISOString();await persist(f,'pending',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:old,deliveryState:'pending'});await persist(f,'delivering',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:old,deliveryState:'delivering'});await persist(f,'delivered-new',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:now,deliveryState:'delivered'});await persist(f,'delivered-old',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:old,deliveryState:'delivered'});const m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,maxCompletedJobs:1,onComplete:()=>{},deliveryEvidence:()=>false});await m.activate();assert.ok(m.status('pending'));assert.ok(m.status('delivering'));assert.ok(m.status('delivered-new'));assert.equal(m.status('delivered-old'),undefined);await m.shutdown()});

test('emergency terminal state wins over stale running state and is delivered once',async t=>{const f=await fixture(t),state=await persist(f,'degraded',{status:'running',pid:999999,pgid:999999,processStartIdentity:'1'}),emergency={...state,status:'failed',classification:'CODEX_REVIEW_STATE_PERSIST_FAILED',completedAt:new Date().toISOString(),deliveryState:'pending'};await writeFile(`${state.stateFile}.emergency`,JSON.stringify(emergency));const notes=[],recorded=new Set(),evidence=id=>recorded.has(id),m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:evidence});await m.activate();assert.equal(notes.length,1);assert.equal(notes[0].classification,'CODEX_REVIEW_STATE_PERSIST_FAILED');recorded.add(notes[0].deliveryId);assert.equal(m.confirmDelivery(notes[0].deliveryId),true);await m.shutdown();const again=[],m2=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>again.push(e),deliveryEvidence:evidence});await m2.activate();assert.equal(again.length,0);await m2.shutdown()});
