import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {mkdtemp,mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import test from 'node:test';
import {CodexReviewJobManager} from '../runtime.ts';

async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'codex-reconcile-'));t.after(()=>rm(root,{recursive:true,force:true}));const cache=path.join(root,'cache'),jobs=path.join(cache,'jobs'),reservations=path.join(cache,'reservations');await mkdir(jobs,{recursive:true});await mkdir(reservations);return{root,cache,jobs,reservations}}
function identity(pid){const raw=readFileSync(`/proc/${pid}/stat`,'utf8'),tail=raw.slice(raw.lastIndexOf(')')+2).split(' ');return{pgid:Number(tail[2]),startTime:tail[19]}}
async function persist(f,name,overrides={}){const output=path.join(f.root,`${name}.md`),reservationFile=path.join(f.reservations,`${name}.reserve`),stateFile=path.join(f.jobs,`${name}.state.json`),jobNonce=`nonce-${name}`;const state={jobId:name,jobNonce,action:'start',reviewType:'implementation-review',verdictProfile:'generic-implementation',status:'starting',summary:'',cwd:f.root,output,stdoutLog:path.join(f.jobs,`${name}.stdout`),stderrLog:path.join(f.jobs,`${name}.stderr`),stateFile,reservationFile,stagingOutput:path.join(f.jobs,`${name}.staging`),launcherStatus:path.join(f.jobs,`${name}.status`),processIdentityFile:path.join(f.jobs,`${name}.identity`),startedAt:new Date().toISOString(),ownerPid:999999,ownerStartIdentity:'1',deliveryId:`delivery-${name}`,deliveryState:'pending',deliveryAttempts:0,...overrides};await writeFile(reservationFile,`${state.jobId}\n${state.jobNonce}\n${state.output}\n`);await writeFile(stateFile,JSON.stringify(state));return state}
async function alive(pid){try{process.kill(pid,0);return true}catch{return false}}
async function waitDead(pid){for(let i=0;i<80;i++){if(!await alive(pid))return;await new Promise(r=>setTimeout(r,25))}throw Error(`pid ${pid} survived`)}

test('startup releases starting ownership and emits one interrupted completion',async t=>{const f=await fixture(t),state=await persist(f,'starting');await writeFile(state.stagingOutput,'x');const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false});await m.activate();assert.equal(m.status('starting').status,'interrupted');assert.equal(notes.length,1);await assert.rejects(readFile(state.reservationFile));await assert.rejects(readFile(state.stagingOutput));await m.shutdown()});

test('startup leaves another live manager ownership and reservation untouched',async t=>{const f=await fixture(t),owner=identity(process.pid),state=await persist(f,'foreign',{ownerPid:process.pid,ownerStartIdentity:owner.startTime});const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false});await m.activate();assert.equal(m.status('foreign'),undefined);assert.equal(notes.length,0);assert.match(await readFile(state.reservationFile,'utf8'),/^foreign/);await m.shutdown()});

test('matching identity and nonce escalates TERM to KILL and waits for exit before delivery',async t=>{const f=await fixture(t),child=spawn('python3',['-c','import signal,time; signal.signal(signal.SIGTERM, signal.SIG_IGN); time.sleep(60)'],{detached:true,stdio:'ignore'});t.after(()=>{try{process.kill(-child.pid,'SIGKILL')}catch{}});await new Promise(r=>setTimeout(r,50));const id=identity(child.pid),state=await persist(f,'matching',{status:'running',pid:child.pid,pgid:id.pgid,processStartIdentity:id.startTime});const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false,killGraceMs:50});await m.activate();await waitDead(child.pid);assert.equal(m.status('matching').classification,'CODEX_REVIEW_INTERRUPTED');assert.equal(notes.length,1);await assert.rejects(readFile(state.reservationFile));await m.shutdown()});

test('dead and mismatched identities are never signalled',async t=>{const f=await fixture(t);await persist(f,'dead',{status:'running',pid:999999,pgid:999999,processStartIdentity:'1'});const child=spawn('python3',['-c','import time; time.sleep(60)'],{detached:true,stdio:'ignore'});t.after(()=>{try{process.kill(-child.pid,'SIGKILL')}catch{}});await new Promise(r=>setTimeout(r,30));const id=identity(child.pid);await persist(f,'mismatch',{status:'running',pid:child.pid,pgid:id.pgid,processStartIdentity:`${id.startTime}x`});const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false,killGraceMs:30});await m.activate();assert.equal(await alive(child.pid),true);assert.equal(m.status('dead').classification,'CODEX_REVIEW_INTERRUPTED');assert.equal(m.status('mismatch').classification,'CODEX_REVIEW_ORPHAN_IDENTITY_UNCERTAIN');assert.equal(notes.length,2);await m.shutdown()});

test('mismatched job nonce preserves another reservation and all failed-cleanup evidence',async t=>{const f=await fixture(t),child=spawn('python3',['-c','import time; time.sleep(60)'],{detached:true,stdio:'ignore'});t.after(()=>{try{process.kill(-child.pid,'SIGKILL')}catch{}});await new Promise(r=>setTimeout(r,30));const id=identity(child.pid),state=await persist(f,'nonce',{status:'running',pid:child.pid,pgid:id.pgid,processStartIdentity:id.startTime});await writeFile(state.reservationFile,`other-job\nother-nonce\n${state.output}\n`);for(const file of [state.stagingOutput,state.launcherStatus,state.processIdentityFile])await writeFile(file,'evidence');const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:()=>false,killGraceMs:30});await m.activate();assert.equal(await alive(child.pid),true);assert.equal(m.status('nonce').classification,'CODEX_REVIEW_ORPHAN_IDENTITY_UNCERTAIN');assert.match(await readFile(state.reservationFile,'utf8'),/^other-job/);for(const file of [state.stagingOutput,state.launcherStatus,state.processIdentityFile])assert.equal(await readFile(file,'utf8'),'evidence');assert.equal(notes.length,1);await m.shutdown()});

test('durable delivery state resolves crash boundaries without zero or duplicate completion',async t=>{const f=await fixture(t);await persist(f,'pending',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:new Date().toISOString(),deliveryState:'pending'});await persist(f,'recorded',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:new Date().toISOString(),deliveryState:'delivering'});await persist(f,'unrecorded',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:new Date().toISOString(),deliveryState:'delivering'});const notes=[],recorded=new Set(['delivery-recorded']),evidence=id=>recorded.has(id);const first=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:evidence});await first.activate();assert.deepEqual(notes.map(x=>x.jobId).sort(),['pending','unrecorded']);assert.equal(first.status('recorded').deliveryState,'delivered');for(const event of notes){recorded.add(event.deliveryId);assert.equal(first.confirmDelivery(event.deliveryId),true)}await first.shutdown();const after=[],second=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>after.push(e),deliveryEvidence:evidence});await second.activate();assert.equal(after.length,0);for(const id of ['pending','recorded','unrecorded'])assert.equal(second.status(id).deliveryState,'delivered');await second.shutdown()});

test('actual top-level custom_message session evidence prevents restart redelivery',async t=>{const f=await fixture(t),state=await persist(f,'top-level',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:new Date().toISOString(),deliveryState:'delivering'}),sessions=path.join(f.root,'sessions');await mkdir(sessions);await writeFile(path.join(sessions,'session.jsonl'),JSON.stringify({type:'custom_message',customType:'codex-review-completion',details:{deliveryId:state.deliveryId}})+'\n');const notes=[],m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,sessionsDir:sessions,onComplete:e=>notes.push(e)});await m.activate();assert.equal(notes.length,0);assert.equal(m.status('top-level').deliveryState,'delivered');await m.shutdown()});

test('retention never prunes pending or delivering exactly-once evidence',async t=>{const f=await fixture(t),now=new Date().toISOString(),old=new Date(Date.now()-10*86400_000).toISOString();await persist(f,'pending',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:old,deliveryState:'pending'});await persist(f,'delivering',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:old,deliveryState:'delivering'});await persist(f,'delivered-new',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:now,deliveryState:'delivered'});await persist(f,'delivered-old',{status:'failed',classification:'CODEX_REVIEW_CODEX_EXIT_NONZERO',completedAt:old,deliveryState:'delivered'});const m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,maxCompletedJobs:1,onComplete:()=>{},deliveryEvidence:()=>false});await m.activate();assert.ok(m.status('pending'));assert.ok(m.status('delivering'));assert.ok(m.status('delivered-new'));assert.equal(m.status('delivered-old'),undefined);await m.shutdown()});

test('emergency terminal state wins over stale running state and is delivered once',async t=>{const f=await fixture(t),state=await persist(f,'degraded',{status:'running',pid:999999,pgid:999999,processStartIdentity:'1'}),emergency={...state,status:'failed',classification:'CODEX_REVIEW_STATE_PERSIST_FAILED',completedAt:new Date().toISOString(),deliveryState:'pending'};await writeFile(`${state.stateFile}.emergency`,JSON.stringify(emergency));const notes=[],recorded=new Set(),evidence=id=>recorded.has(id),m=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>notes.push(e),deliveryEvidence:evidence});await m.activate();assert.equal(notes.length,1);assert.equal(notes[0].classification,'CODEX_REVIEW_STATE_PERSIST_FAILED');recorded.add(notes[0].deliveryId);assert.equal(m.confirmDelivery(notes[0].deliveryId),true);await m.shutdown();const again=[],m2=new CodexReviewJobManager({launcherPath:'/bin/false',cacheDir:f.cache,onComplete:e=>again.push(e),deliveryEvidence:evidence});await m2.activate();assert.equal(again.length,0);await m2.shutdown()});
